spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gasymovrv/piggymetrics-config-repo.git
          clone-on-start: true
          username: ${CONFIG_REPO_USER}
          password: ${CONFIG_REPO_PASSWORD}
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

